compile_knapsack_3: knapsack_3D_v3.c utils_boxes.c sa_performance_stuff.c local_optimum_utils.c upgrades_v2.c
	gcc -g knapsack_3D_v3.c utils_boxes.c sa_performance_stuff.c local_optimum_utils.c upgrades_v2.c -lm -o knapsack_3D_v3.out
