compile_knapsack_1: main.c utils.c extreme_points.c boxes.c knapsack_0_1_solver.c
	gcc -g main.c utils.c extreme_points.c boxes.c knapsack_0_1_solver.c -lm -o main.out

compile_prova: prova.c utils.c extreme_points.c knapsack_0_1_solver_2.c
	gcc -g prova.c utils.c extreme_points.c knapsack_0_1_solver_2.c -lm -o prova.out