compile_knapsack_1: knapsack_3D_v1.c utils_boxes.c 
	gcc knapsack_3D_v1.c utils_boxes.c -lm -o knapsack_3D_v1.out

compile_knapsack_2:
	gcc -g knapsack_3D_v2.c utils_boxes.c sa_performance_stuff.c local_optimum_utils.c -lm -o knapsack_3D_v2.out
